// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  sequence: __t.u64(),
  actorType: __t.string().name("actor_type"),
  actorId: __t.option(__t.u64()).name("actor_id"),
  eventType: __t.string().name("event_type"),
  displayText: __t.string().name("display_text"),
  createdAt: __t.timestamp().name("created_at"),
});
