// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  itemId: __t.option(__t.u64()).name("item_id"),
  criterionId: __t.option(__t.u64()).name("criterion_id"),
  text: __t.string(),
  evidenceType: __t.string().name("evidence_type"),
  status: __t.string(),
  createdBy: __t.string().name("created_by"),
  sourceEventId: __t.option(__t.u64()).name("source_event_id"),
});
