// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  templateKey: __t.string().name("template_key"),
  title: __t.string(),
  decisionQuestion: __t.string().name("decision_question"),
  objective: __t.string(),
  decisionRule: __t.string().name("decision_rule"),
  capacityTotal: __t.u32().name("capacity_total"),
  status: __t.string(),
  contractVersion: __t.u64().name("contract_version"),
  proposalVersion: __t.u64().name("proposal_version"),
  facilitatorIdentity: __t.identity().name("facilitator_identity"),
  createdAt: __t.timestamp().name("created_at"),
  decidedAt: __t.option(__t.timestamp()).name("decided_at"),
});
