// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActivityEvent = __t.object("ActivityEvent", {
  id: __t.u64(),
  roomId: __t.u64(),
  sequence: __t.u64(),
  actorType: __t.string(),
  actorId: __t.option(__t.u64()),
  eventType: __t.string(),
  displayText: __t.string(),
  createdAt: __t.timestamp(),
});
export type ActivityEvent = __Infer<typeof ActivityEvent>;

export const AiState = __t.object("AiState", {
  roomId: __t.u64(),
  state: __t.string(),
  detail: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AiState = __Infer<typeof AiState>;

export const Approval = __t.object("Approval", {
  id: __t.u64(),
  roomId: __t.u64(),
  proposalVersion: __t.u64(),
  participantId: __t.u64(),
  state: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Approval = __Infer<typeof Approval>;

export const ConversationEvent = __t.object("ConversationEvent", {
  id: __t.u64(),
  roomId: __t.u64(),
  sequence: __t.u64(),
  speakerLabel: __t.option(__t.string()),
  text: __t.string(),
  isFinal: __t.bool(),
  createdAt: __t.timestamp(),
});
export type ConversationEvent = __Infer<typeof ConversationEvent>;

export const Criterion = __t.object("Criterion", {
  id: __t.u64(),
  roomId: __t.u64(),
  label: __t.string(),
  criterionType: __t.string(),
  status: __t.string(),
  createdBy: __t.string(),
});
export type Criterion = __Infer<typeof Criterion>;

export const Evidence = __t.object("Evidence", {
  id: __t.u64(),
  roomId: __t.u64(),
  itemId: __t.option(__t.u64()),
  criterionId: __t.option(__t.u64()),
  text: __t.string(),
  evidenceType: __t.string(),
  status: __t.string(),
  createdBy: __t.string(),
  sourceEventId: __t.option(__t.u64()),
});
export type Evidence = __Infer<typeof Evidence>;

export const Item = __t.object("Item", {
  id: __t.u64(),
  roomId: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  itemType: __t.string(),
  effort: __t.u32(),
  status: __t.string(),
  createdBy: __t.string(),
  sourceEventId: __t.option(__t.u64()),
});
export type Item = __Infer<typeof Item>;

export const Participant = __t.object("Participant", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  roleLabel: __t.string(),
  connected: __t.bool(),
  contractAcceptedVersion: __t.u64(),
  joinedAt: __t.timestamp(),
});
export type Participant = __Infer<typeof Participant>;

export const Position = __t.object("Position", {
  id: __t.u64(),
  roomId: __t.u64(),
  participantId: __t.u64(),
  itemId: __t.u64(),
  stance: __t.string(),
  note: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type Position = __Infer<typeof Position>;

export const ProposalItem = __t.object("ProposalItem", {
  id: __t.u64(),
  roomId: __t.u64(),
  proposalVersion: __t.u64(),
  itemId: __t.u64(),
  disposition: __t.string(),
  orderIndex: __t.u32(),
  effortCommitted: __t.u32(),
});
export type ProposalItem = __Infer<typeof ProposalItem>;

export const ProposalItemInput = __t.object("ProposalItemInput", {
  itemId: __t.u64(),
  disposition: __t.string(),
  orderIndex: __t.u32(),
});
export type ProposalItemInput = __Infer<typeof ProposalItemInput>;

export const Relation = __t.object("Relation", {
  id: __t.u64(),
  roomId: __t.u64(),
  fromItemId: __t.u64(),
  toItemId: __t.u64(),
  relationType: __t.string(),
  status: __t.string(),
  createdBy: __t.string(),
  sourceEventId: __t.option(__t.u64()),
});
export type Relation = __Infer<typeof Relation>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  templateKey: __t.string(),
  title: __t.string(),
  decisionQuestion: __t.string(),
  objective: __t.string(),
  decisionRule: __t.string(),
  capacityTotal: __t.u32(),
  status: __t.string(),
  contractVersion: __t.u64(),
  proposalVersion: __t.u64(),
  facilitatorIdentity: __t.identity(),
  createdAt: __t.timestamp(),
  decidedAt: __t.option(__t.timestamp()),
});
export type Room = __Infer<typeof Room>;

