// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptDecisionContractReducer from "../accept_decision_contract_reducer";
import AddEvidenceReducer from "../add_evidence_reducer";
import AppendActivityEventReducer from "../append_activity_event_reducer";
import AppendConversationEventReducer from "../append_conversation_event_reducer";
import ApproveProposalReducer from "../approve_proposal_reducer";
import CreateConversationRoomReducer from "../create_conversation_room_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LoadPmDemoReducer from "../load_pm_demo_reducer";
import PublishCandidateProposalReducer from "../publish_candidate_proposal_reducer";
import PublishProposalReducer from "../publish_proposal_reducer";
import ReplaceDiscussionPointsReducer from "../replace_discussion_points_reducer";
import RequestProposalChangeReducer from "../request_proposal_change_reducer";
import ReviewCriterionReducer from "../review_criterion_reducer";
import ReviewEvidenceReducer from "../review_evidence_reducer";
import ReviewItemReducer from "../review_item_reducer";
import ReviewRelationReducer from "../review_relation_reducer";
import SetAiStateReducer from "../set_ai_state_reducer";
import SetPositionReducer from "../set_position_reducer";
import SetPresenceReducer from "../set_presence_reducer";
import SetProposalItemsReducer from "../set_proposal_items_reducer";
import SuggestCriterionReducer from "../suggest_criterion_reducer";
import SuggestEvidenceReducer from "../suggest_evidence_reducer";
import SuggestItemReducer from "../suggest_item_reducer";
import SuggestRelationReducer from "../suggest_relation_reducer";
import UpdateDecisionContractReducer from "../update_decision_contract_reducer";

export type AcceptDecisionContractParams = __Infer<typeof AcceptDecisionContractReducer>;
export type AddEvidenceParams = __Infer<typeof AddEvidenceReducer>;
export type AppendActivityEventParams = __Infer<typeof AppendActivityEventReducer>;
export type AppendConversationEventParams = __Infer<typeof AppendConversationEventReducer>;
export type ApproveProposalParams = __Infer<typeof ApproveProposalReducer>;
export type CreateConversationRoomParams = __Infer<typeof CreateConversationRoomReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LoadPmDemoParams = __Infer<typeof LoadPmDemoReducer>;
export type PublishCandidateProposalParams = __Infer<typeof PublishCandidateProposalReducer>;
export type PublishProposalParams = __Infer<typeof PublishProposalReducer>;
export type ReplaceDiscussionPointsParams = __Infer<typeof ReplaceDiscussionPointsReducer>;
export type RequestProposalChangeParams = __Infer<typeof RequestProposalChangeReducer>;
export type ReviewCriterionParams = __Infer<typeof ReviewCriterionReducer>;
export type ReviewEvidenceParams = __Infer<typeof ReviewEvidenceReducer>;
export type ReviewItemParams = __Infer<typeof ReviewItemReducer>;
export type ReviewRelationParams = __Infer<typeof ReviewRelationReducer>;
export type SetAiStateParams = __Infer<typeof SetAiStateReducer>;
export type SetPositionParams = __Infer<typeof SetPositionReducer>;
export type SetPresenceParams = __Infer<typeof SetPresenceReducer>;
export type SetProposalItemsParams = __Infer<typeof SetProposalItemsReducer>;
export type SuggestCriterionParams = __Infer<typeof SuggestCriterionReducer>;
export type SuggestEvidenceParams = __Infer<typeof SuggestEvidenceReducer>;
export type SuggestItemParams = __Infer<typeof SuggestItemReducer>;
export type SuggestRelationParams = __Infer<typeof SuggestRelationReducer>;
export type UpdateDecisionContractParams = __Infer<typeof UpdateDecisionContractReducer>;

